### ISSUE TITLE
groovy gradle snippets missing

### ISSUE THREAD

**Issue by timo-a** [springdoc/springdoc-openapi-gradle-plugin#35]
Running `generateOpenApiDocs` with defaults works for me, but once I add code to my gradle.build I run into problems:
When I add:
```
openApi {
    apiDocsUrl.set("https://localhost:8080/v3/api-docs")
    outputDir.set(file("$buildDir/docs"))
    outputFileName.set("myopenapi.json")
    waitTimeInSeconds.set(10)
    forkProperties.set("-Dspring.profiles.active=special")
}
```
(https://github.com/timo-a/duckpond-spring-backend/tree/49aa3398f980b17a63973b5952a8eb47429a2f72)  

I get:

```
2020-11-23 00:39:02.977  INFO 71172 --- [nio-8080-exec-1] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.

java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x030x010x930x010x000x010x8f0x030x03w0xad0x84@0xcci0xcf0x9b0x98|R0x94%0xb80x810x190xc90xa60x7fs>0x97J7.0xfc0x940xc30xf9r5N]. HTTP method names must be tokens
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:417) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:261) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]

> Task :generateOpenApiDocs FAILED
> Task :stopForkedSpringBoot

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateOpenApiDocs'.
> javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
```

I think it could be because the readme features snippets in kotlin whereas I use groovy for gradle. If so I don't know how to correctly write this in groovy:
```
openApi {
    apiDocsUrl = "https://localhost:8080/v3/api-docs"
}
```
(https://github.com/timo-a/duckpond-spring-backend/tree/22d8f4992a098845ba246aeb024f5cd7c4f0d350)  
gives a similar error.  
If you know how to do this in groovy I think it would help a lot if you spelled it out.

**Comment by kpramesh2212** [comment]
can you please try removing https and use http instead.
