### ISSUE TITLE
NPE when generating documentation

### ISSUE THREAD

**Issue by MLNW** [springdoc/springdoc-openapi-gradle-plugin#72]
I just tried to generate some OpenAPI documentation via this plugin and I receive the following error:

```console
java.lang.NullPointerException: null
        at org.springdoc.api.OpenApiResource.calculatePath(OpenApiResource.java:96) ~[springdoc-openapi-core-1.1.49.jar!/:na]
        at org.springdoc.api.OpenApiResource.getPaths(OpenApiResource.java:82) ~[springdoc-openapi-core-1.1.49.jar!/:na]
        at org.springdoc.api.AbstractOpenApiResource.getOpenApi(AbstractOpenApiResource.java:79) ~[springdoc-openapi-common-1.1.49.jar!/:na]
        at org.springdoc.api.OpenApiResource.openapiJson(OpenApiResource.java:66) ~[springdoc-openapi-core-1.1.49.jar!/:na]
```

After some investigation I found that the `springdoc-openapi-core` dependency is unmaintained as its [Last Release was on Oct 21, 2019](https://mvnrepository.com/artifact/org.springdoc/springdoc-openapi-core).

Since the last time this setup worked we upgraded our Spring Boot version to `2.6.2`. I'm guessing that is a culprit in tandem with the very old versions in use.

**Comment by bnasslahsen** [comment]
@MLNW, 

As mentioned in the [contribution guide](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc), before opening tickets, make sure you use the last available release.

See the documentation here to use `v1.6.6`: https://springdoc.org/
