### ISSUE TITLE
Api has username and password

### ISSUE THREAD

**Issue by mo-hse** [springdoc/springdoc-openapi-gradle-plugin#82]
how should the documentation generation be if there is the api has username and password?
currently for me it waits for the timeout period before the generation fails, any idea way how to set username and password ?

`> Task :generateOpenApiDocs FAILED
Unable to connect to http://localhost:8080/myapi/docs waited for 30 seconds
org.awaitility.core.ConditionTimeoutException: Condition org.awaitility.kotlin.AwaitilityKt$sam$java_util_concurrent_Callable$0 was not fulfilled within 30 seconds.
        at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:165)
        at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
        at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
        at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:895)
        at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:864)
        at org.awaitility.kotlin.AwaitilityKt.until(AwaitilityKt.kt:137)
        at org.springdoc.openapi.gradle.plugin.OpenApiGeneratorTask.generateApiDocs(OpenApiGeneratorTask.kt:69)
        at org.springdoc.openapi.gradle.plugin.OpenApiGeneratorTask.execute(OpenApiGeneratorTask.kt:60)
        at java.base@17/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base@17/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base@17/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base@17/java.lang.reflect.Method.invoke(Method.java:568)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
`

**Comment by bnasslahsen** [comment]
This is related to your project configuration.
You can pass your credentials via many ways, for example system properties. 
But your description is not enough to provide you any further guidance.
